name: Rust

permissions:
  contents: read

on:
  push:
    tags:
      - v[0-9]+.*

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # for taiki-e/create-gh-release-action
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/create-gh-release-action@v1
        with:
          # (optional) Path to changelog.
          changelog: CHANGELOG.md

  upload-assets:
    needs: create-release
    runs-on: ubuntu-latest
    permissions:
      contents: write # for taiki-e/upload-rust-binary-action
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          # (required) Binary names (non-extension portion of filename) to build and upload (whitespace or comma separated list).
          # Note that glob pattern is not supported yet.
          bin: awoo
